### ISSUE TITLE
Is it possible to output Github-style shortcode instead of the actual emoji character?

### ISSUE THREAD

**Issue by mrmartineau** [ethanal/SublimeEmoji#2]
As the title says, I think it would be nice to output the Github-style shortcode instead of the emoji character? Is that possible? Perhaps ithe output style could be a setting...?

Some more info:
- https://developer.github.com/v3/emojis/
- http://www.emoji-cheat-sheet.com/

Cheers mate, and thanks for the plugin

**Comment by dhulihan** [comment]
https://github.com/akatopo/GithubEmoji

**Comment by mrmartineau** [comment]
Ah, thanks!
